# Site settings
title: Pattern, by Golin Digital
email: tedwards@golin.com
description: > # this means to ignore newlines until "baseurl:"
  Processes and best practices for making things awesome.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://golincode.github.io/pattern" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  jekyll
theme: minima

# Build settings
markdown: kramdown
